table 'General Ledger'
	lineageTag: 237cb2fe-e169-45cc-bd44-03ccb6304898

	measure 'GL Amount' = VAR s =   SELECTEDVALUE(Scenario[Scenario],"Actual") RETURN   CALCULATE(sum('General Ledger'[BaseAmount] ), Scenario[Scenario] =s) * 'Finanical Report'[Report Scope]
		formatString: #,0
		lineageTag: 38e3580e-4e18-486b-aa59-f6f688a73558

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'GL Budget' = VAR s =   SELECTEDVALUE(Scenario[Scenario],"Budget") RETURN   CALCULATE(sum('General Ledger'[BaseAmount] ), Scenario[Scenario] =s) * 'Finanical Report'[Report Scope]
		formatString: #,0
		lineageTag: 5b5cbaa1-da3f-4655-8828-7d39af75ec55

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'GL Variance' = [GL Amount] -[GL Budget]
		formatString: #,0
		lineageTag: 8d8acf0c-b2e7-4495-b34b-5a542341476e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'GL Variance%' = DIVIDE([GL Variance] ,[GL Budget])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: f2ff6259-2b0d-4020-88ab-c82d47c935f2

	measure 'Base Amount' = sum('General Ledger'[BaseAmount])
		isHidden
		lineageTag: 2b2699b8-41d4-414e-b7fb-47362e26483f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GL Opening Balance' = var MaxPeriod =MIN('Date'[Fiscal Period No] ) RETURN CALCULATE( [GL Amount] , all('Date'), 'Date'[Fiscal Period No] < MaxPeriod)
		formatString: #,0
		lineageTag: 41b2a836-a92b-4c98-b64a-c96161ccab12

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'GL Closing Balance' = var MaxPeriod =max('Date'[Fiscal Period No] ) RETURN CALCULATE( [GL Amount] , all('Date'), 'Date'[Fiscal Period No] <= MaxPeriod)
		formatString: #,0
		lineageTag: 87bf7b0c-93b8-4058-b83e-665c595b53c3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'GL Movement' = ```
			[GL Amount] 
			```
		formatString: #,0
		lineageTag: 2029804e-0c9f-497a-80e6-b1e5cdde63d5

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'CashFlow Amount' = SWITCH(SELECTEDVALUE('Finanical Report'[Operator]), "DaxSubTotal", [DaxSubTotal] , "Reconciliation",[Reconciliation],[CashFlow Base]) * 'Finanical Report'[Report Scope]
		formatString: #,0
		lineageTag: 2715700b-e1c8-42f7-9284-a7503e365c63

		annotation PBI_FormatHint = {"isDecimal":true}

	measure LinkAmount =
			
			VAR l =
			    MAX ( 'Finanical Report'[LinkLineNo] )
			VAR r =
			    SELECTEDVALUE ( 'Finanical Report'[LinkReport] )
			RETURN
			    CALCULATE (
			        IF ( LEFT ( r, 2 ) = "BS",   [GL Movement], [GL Amount] ),
			        ALLEXCEPT (
			            'Finanical Report',
			            'Finanical Report'[LineNo],
			            'Finanical Report'[LinkReport]
			        ),
			        'Finanical Report'[LineNo] = l,
			        'Finanical Report'[Report] = r
			    ) * max('Finanical Report'[Link Signage])
		formatString: #,0
		displayFolder: _Internal
		lineageTag: c4e25950-c995-431d-b825-61e1a5ad3f7c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure LinkGroup =
			
			VAR l =
			    MAX ( 'Finanical Report'[LinkHeading] )
			VAR r =
			    SELECTEDVALUE ( 'Finanical Report'[LinkReport] )
			RETURN
			    CALCULATE (
			        IF ( LEFT ( r, 2 ) = "BS", [GL Movement], [GL Amount] ),
			        ALLEXCEPT (
			            'Finanical Report',
			            'Finanical Report'[LinkHeading],
			            'Finanical Report'[LinkReport]
			        ),
			        'Finanical Report'[Report Heading] = l,
			        'Finanical Report'[Report] = r
			    )* max('Finanical Report'[Link Signage])
		formatString: #,0
		displayFolder: _Internal
		lineageTag: 1db4e718-cd7e-4382-bc72-dd638b40aefa

		annotation PBI_FormatHint = {"isDecimal":true}

	measure DaxSubTotal = CALCULATE(  SUMX(values ('Finanical Report'[LineNo]),   [CashFlow Base] ), ALLEXCEPT('Finanical Report', 'Finanical Report'[ReportHeadingNo] , 'Finanical Report'[Report]))
		formatString: 0
		displayFolder: _Internal
		lineageTag: 005e92db-3e36-4c1a-a6b7-327195e7fe9b

	measure DaxRunningSum = ```
			VAR l=SELECTEDVALUE('Finanical Report'[LineNo]) RETURN CALCULATE( SUMX(VALUES('Finanical Report'[LineNo]),  [LinkAmount]+ [LinkGroup]) , ALLEXCEPT('Finanical Report', 'Finanical Report'[Report]), 'Finanical Report'[LineNo] < l, 'Finanical Report'[Operator]  <> "DaxRunningSum" , 'Finanical Report'[Operator] <> "OpeningBalance") 
			```
		formatString: 0
		displayFolder: _Internal
		lineageTag: fc719e72-4b21-47c3-9c67-675ef5e3cb60

	measure LinkOpenBalance =
			
			VAR l =
			    MAX ( 'Finanical Report'[LinkLineNo] )
			VAR r =
			    SELECTEDVALUE ( 'Finanical Report'[LinkReport] )
			RETURN
			    CALCULATE (
			        [GL Opening Balance],
			        ALLEXCEPT (
			            'Finanical Report',
			            'Finanical Report'[LineNo],
			            'Finanical Report'[LinkReport]
			        ),
			        'Finanical Report'[LineNo] = l,
			        'Finanical Report'[Report] = r
			    ) * max('Finanical Report'[Link Signage])
		formatString: 0
		displayFolder: _Internal
		lineageTag: f699e5a1-a1bf-4a9b-b251-af091be22a6a

	measure LinkClosingBalance =
			
			VAR l =
			    MAX ( 'Finanical Report'[LinkLineNo] )
			VAR r =
			    SELECTEDVALUE ( 'Finanical Report'[LinkReport] )
			RETURN
			    CALCULATE (
			        [GL Closing Balance],
			        ALLEXCEPT (
			            'Finanical Report',
			            'Finanical Report'[LineNo],
			            'Finanical Report'[LinkReport]
			        ),
			        'Finanical Report'[LineNo] = l,
			        'Finanical Report'[Report] = r
			    ) * max('Finanical Report'[Link Signage])
		formatString: "€"#,0.###############;-"€"#,0.###############;"€"#,0.###############
		displayFolder: _Internal
		lineageTag: d1ffb3a4-5500-4c1b-a3fe-96802ac14a67

		annotation PBI_FormatHint = {"currencyCulture":"en-IE"}

	measure 'CashFlow Base' = SWITCH(SELECTEDVALUE('Finanical Report'[Operator]),"Link", [LinkAmount],  "OpeningBalance", [LinkOpenBalance], "ClosingBalance", [LinkClosingBalance], "LinkGroup", [LinkGroup]  , "DaxRunningSum",[DaxRunningSum]  )  * 'Finanical Report'[Report Scope]
		formatString: 0
		displayFolder: _Internal
		lineageTag: 4b97d575-2d5d-4922-9f25-cf3541dc7c02

	measure Reconciliation = CALCULATE( [DaxRunningSum], ALLEXCEPT('Finanical Report', 'Finanical Report'[Report]),  'Finanical Report'[LineNo]=19)  + CALCULATE([GL Opening Balance] , all('Finanical Report'), 'Finanical Report'[Report Section] ="Cash")  - CALCULATE([GL Closing Balance] , all('Finanical Report'), 'Finanical Report'[Report Section] ="Cash")
		formatString: 0
		lineageTag: 855c177c-7bd5-4fcd-addd-80fd400009ce

	column DateKey
		dataType: string
		isHidden
		lineageTag: 98f96fe9-728e-4c09-9ac3-dabe69a7f796
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrganizationKey
		dataType: string
		isHidden
		lineageTag: 5c194de1-7534-4706-9d36-cda2ddf91979
		summarizeBy: none
		sourceColumn: OrganizationKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DepartmentGroupKey
		dataType: string
		isHidden
		lineageTag: a4be9d1c-f002-430e-b38d-c8e1bfd9fab1
		summarizeBy: none
		sourceColumn: DepartmentGroupKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ScenarioKey
		dataType: string
		isHidden
		lineageTag: 6e2730af-a4f6-4c4c-a05a-a200d40cff00
		summarizeBy: none
		sourceColumn: ScenarioKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AccountKey
		dataType: string
		isHidden
		lineageTag: ecbf2a4c-b24c-4bc3-8e9c-39636525c1fc
		summarizeBy: none
		sourceColumn: AccountKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: string
		isHidden
		lineageTag: d5802c42-3fa9-41d7-b42a-c651cb47794d
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BaseAmount
		dataType: double
		isHidden
		formatString: "€"#,0.###############;-"€"#,0.###############;"€"#,0.###############
		lineageTag: 87078bb8-3510-4993-9e23-d23ac6e123ec
		summarizeBy: none
		sourceColumn: BaseAmount

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-IE"}

	partition 'General Ledger-d699db49-9681-49fc-b81e-bf1140f35c13' = m
		mode: import
		queryGroup: 'Finance GL'
		source =
				let
				    Source = Sql.Database("fkm4vwf6l6zebg4lqrhbtdcmsq-yctecwmyrr4u3mdfun4j5hqjma.datawarehouse.fabric.microsoft.com", "DW", [Query="SELECT DateKey, DepartmentGroupKey, ScenarioKey, OrganizationKey, BaseAmount, AccountKey, Date FROM reports.FactFinance f"])
				in
				    Source

	annotation PBI_ResultType = Table

	annotation LinkedQueryName = General Ledger

	annotation PBI_NavigationStepName = Navigation

