CREATE TABLE [config].[edwTables] (
    [TableID]             SMALLINT       NOT NULL,
    [SchemaName]          VARCHAR (128)  NULL,
    [TableName]           VARCHAR (128)  NULL,
    [LoadDescription]     VARCHAR (512)  NULL,
    [TableType]           VARCHAR (20)   NULL,
    [SourceObject]        VARCHAR (8000) NULL,
    [SourceType]          VARCHAR (20)   NULL,
    [BusinessKeys]        VARCHAR (512)  NULL,
    [PrimaryKey]          VARCHAR (512)  NULL,
    [DefaultPackageGroup] VARCHAR (50)   NULL,
    [TablePrefix]         VARCHAR (10)   NULL,
    [Enabled]             BIT            NULL,
    [InsertFlag]          BIT            NULL,
    [UpdateFlag]          BIT            NULL,
    [DeleteFlag]          BIT            NULL,
    [DedupeRows]          BIT            NULL,
    [AutoDrop]            BIT            NULL,
    [CTAS]                BIT            NULL,
    [AutoTruncate]        BIT            NULL,
    [DeleteDDL]           VARCHAR (8000) NULL,
    [SkipSqlCondition]    VARCHAR (8000) NULL,
    [PrestageSourceFlag]  BIT            NULL,
    [PrestageTargetFlag]  BIT            NULL,
    [PrestageSchema]      VARCHAR (8000) NULL,
    [PrestageTable]       VARCHAR (8000) NULL,
    [DeltaTargetObject]   VARCHAR (8000) NULL,
    [PreLoadSQL]          VARCHAR (8000) NULL,
    [PostLoadSQL]         VARCHAR (8000) NULL,
    [WhereSQL]            VARCHAR (8000) NULL,
    [JoinType]            VARCHAR (8000) NULL,
    [Language]            VARCHAR (8000) NULL,
    [SchemaDrift]         BIT            NULL,
    [IsIncremental]       BIT            NULL,
    [SCD]                 BIT            NULL,
    [Identity]            BIT            NULL,
    CONSTRAINT [PK_edwTables] PRIMARY KEY CLUSTERED ([TableID] ASC)
);


GO

